/**
 * Removes all HTML tags and returns plain text.
 */
export function stripHtml(html: string): string {
    if (!html) return '';
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;
    return tempDiv.textContent || tempDiv.innerText || '';
}

/**
 * Removes only <img> tags from the HTML.
 */
export function removeImages(html: string): string {
    if (!html) return '';
    return html.replace(/<img[^>]*>/gi, '');
}

/**
 * Checks if the HTML contains any <img> tags.
 */
export function hasImages(html: string): boolean {
    if (!html) return false;
    return /<img[^>]*>/i.test(html);
}

/**
 * Counts the approximate number of visual lines generated by block or break tags.
 */
export function countHtmlLines(html: string): number {
    if (!html) return 0;
    const matches = html.match(/<(p|div|h[1-6]|li|br)[^>]*>/gi);
    return matches ? Math.max(1, matches.length) : 1;
}
